#!/bin/bash

export scriptName=`basename "${BASH_SOURCE[0]}"`
usage()
{
	echo "usage:"
	echo ;  echo "$scriptName \"*.mhd\"  \"X\" binary";  echo
	echo "Arguments (all optional):"
	echo "  arg1: name of images to run flow simulations on (defaults is *.mhd)"
	echo "  arg2: flow direction(s):  any combination of X Y Z"
	echo "  arg3: output format for FOAM2Voxel: \".dat\", \".raw\" , \".tif\" (default), "
	echo "        or \"oldAscii\" (for compatibility with old IC codes)" 
	echo "Example:" 
	echo "$scriptName \"\$(ls *.mhd)\"" 
}
if [ "$1" == "" ]; then usage; fi
if [ "$1" == "-h" ]; then usage; exit; fi
if [ "$1" == "--help" ]; then usage; exit; fi
if [ -n "$2" ] ; then 
	if [[ $2 != [XYZ] ]]; then echo "Error: \$2 ($2) can be X Y or Z only ";  exit; fi 
fi
echo $scriptName $@
echo



: ${nProcX:=4}
: ${nProcY:=4}
: ${nProcZ:=2}
echo "nProcessors: $nProcX x $nProcY x $nProcZ "



baseCase="base"

myCurrentDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )
: ${msSrc:=$myCurrentDIR} ; export msSrc

#dataFiles="Berea.mhd" 
if [ -n "$1" ]; then  dataFiles=$1
else                  dataFiles="$(ls *.mhd)"
fi
echo "Images: $dataFiles"

: ${directions:=$2}
: ${directions:=X}
  echo "flow directions=\"$directions\" "

: ${outPutFormat:=$3}
: ${outPutFormat:=tif}
  echo "outPutFormat=\"$outPutFormat\" "


#~ maxDeltaT="2e-5"
endTime=.1


ps=" 1"


. $msSrc/script/initbash



for datFile in $dataFiles
do
dataFile=${datFile%.*}

prefix="$dataFile/"
mkdir $prefix


for direction in $directions
do
echo "direction $direction"

for p in $ps
do
echo "p @ $direction : $p  Pa"

  caseName="$prefix""$dataFile-$p""-$direction"
  if  ! [ -d $caseName ]; then 
	#~ LAM_MPI_SESSION_SUFFIX="$(echo $caseName | sed 's/\///g')"
	#~ echo $LAM_MPI_SESSION_SUFFIX
	#~ lamboot -v machines.txt 

	if  ! [ -f $dataFile.mhd ]; then 
	 if   [ -f $dataFile.nhdr ]; then 
	  echo "ObjectType =  Image" >  $dataFile.mhd
	  echo "NDims =       3"     >>  $dataFile.mhd
	  echo "ElementType = MET_UCHAR"  >>  $dataFile.mhd
	  echo ""  >>  $dataFile.mhd
	  tmpp=`more $dataFile.nhdr | grep sizes |  sed 's/sizes/ /'  |  sed 's/:/ /'`
	  echo $tmpp
	  echo "DimSize =  $tmpp" >>  $dataFile.mhd
	  tmpp=$(more $dataFile.nhdr | grep directions |  sed 's/directions/ /' |  sed 's/space//'  |  sed 's/:/ /') 
	  echo $tmpp
	  echo  >>  $dataFile.mhd
	  echo "ElementSize =  $tmpp" | sed 's/\,/ /g' | sed 's/)/ /g' | sed 's/(/ /g' | sed 's/ 0 / /g' | sed 's/ 0 / /g' >>  $dataFile.mhd
	  echo "Offset = 0 0 0" >>  $dataFile.mhd
	  echo ""  >>  $dataFile.mhd
	  echo "ElementDataFile = $datFile"  >>  $dataFile.mhd
	  echo ""  >>  $dataFile.mhd
	 else
		echo "can not find the file  $dataFile.mhd nor  $dataFile.nhdr"
		exit
	 fi
	fi







	cp -r $SP_SCRIPTS/base $caseName


	(cd $caseName/0 && mv p.$direction p)
	(cd $caseName/0 && rm p.*)
	(cd $caseName/0 && mv U.$direction U)
	(cd $caseName/0 && rm U.*)


	cp $dataFile.mhd $caseName/${dataFile}_input.mhd
	sed -i 's/^ElementDataFile[ \t]*=[ \t]*/ElementDataFile = ..\/..\//'  $caseName/${dataFile}_input.mhd
	(cd $caseName && runApp voxelToFoamPar  ${dataFile}_input.mhd $nProcX $nProcY $nProcZ )
	(cd $caseName &&  for processorDir in `ls -d processo*[0-9] 2>/dev/null` ; do  cp -r 0 "$processorDir" ;    done )
	nlProc=`cd $caseName && ls -d -1 processo*[0-9] 2>/dev/null | sed 's/processor//g' | sort -n -r | head -n 1`
	nProc=$[nlProc+1]
	echo nProc $nProc
	setKeywordValues numberOfSubdomains $nProc ./$caseName/system/decomposeParDict 



	(cd $caseName && touch ${caseName//\//-}.foam)



	setBoundaryCondition "$direction"  "value" "uniform  $p" ./$caseName/0/p 


	#(cd $caseName && runMPI redistributePar $nProc -overwrite)
	(cd $caseName && runMPI renumberMesh $nProc -overwrite)


	setKeywordValues endTime $endTime ./$caseName/system/controlDict 

	#setKeywordValues writeFormat ascii ./$caseName/system/controlDict 

	(cd $caseName && runMPI iPotentialFoam $nProc)

	#setKeywordValues writeFormat binary ./$caseName/system/controlDict 

	setSubKeywordValues relaxationFactors "U" "0.5" ./$caseName/system/fvSolution

	setKeywordValues writeInterval 1000 ./$caseName/system/controlDict 
	echo "..................Running single phase flow code......................."
	(cd $caseName && runMPI icoNSFoam $nProc)
	(cd $caseName && mv log.icoNSFoam log.icoNSFoam.1)

	#setSubKeywordValues relaxationFactors "U" "0.4" ./$caseName/system/fvSolution
	#setKeywordValues writeInterval 100 ./$caseName/system/controlDict 
	#(cd $caseName && runMPI icoNSFoam $nProc)
	#(cd $caseName && mv log.icoNSFoam log.icoNSFoam.2)



	#(cd $caseName && runMPI calc_perms $nProc)
	(cd $caseName && runMPI calc_distributions $nProc)

	(cd $caseName && runApp  FOAM2VoxelSaveMemory vxlImage.mhd "$nProc" "$outPutFormat")


	echo "..................            END              ......................."

	#~ lamhalt -d
   else
     echo "skipping $caseName"
   fi
done
done
done




