#!/bin/sh
# Source tutorial run functions
#~ . $WM_PROJECT_DIR/bin/tools/RunFunctions


if [ -n "$1" ]; then
    dataFiles=$1
else
    dataFiles="."
fi


#mkdir BereaSmallForCX1
for case in $dataFiles
do
if [ -d $case ]; then

    latestTime="$(cd ${case} && ls -d -1 [0-9]* | sed '/[a-z]/d' | sort -n -r | head -n 1 | sort -n | head -n 1)"
    echo "${case}/$latestTime"
    processorDirs="$(cd ${case} && ls -d processo*[0-9])"
    for processorDir in $processorDirs
    do
    latestTime="$(cd ${case}/$processorDir && ls -d -1 [0-9]* | sed '/[a-z]/d'| sort -n -r | head -n 1 | sort -n | head -n 1)"

        echo "$processorDir/$latestTime"
    done

fi
done

