#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmakeLnInclude decompositionMethods

echo "deactivated: metisDecomp parMetisDecomp scotchDecomp"
#wmakeLnInclude metisDecomp
#wmakeLnInclude parMetisDecomp
#wmakeLnInclude scotchDecomp
