/*---------------------------------------------------------------------------*\
License:
	Same as the files #included below.

Description
	 Converts compactFaceList  format, generated by  by OpenFOAM Foundation or
	 by ESI OpenCFD releases of OpenFOAM, to faceList for use in foam-extend.

\*---------------------------------------------------------------------------*/

#include "argList.H"
#include "Time.H"

#include "OFstream.H"
#include "faceIOList.H"

using namespace Foam;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
// Main program:

int main(int argc, char *argv[])
{
#   include "setRootCase.H"
#   include "createTime.H"

    objectRegistry registry(runTime);
    faceCompactIOList facesCompact
    (
         IOobject
         (
             "faces",
             "constant",
             "polyMesh",
             runTime,
             IOobject::MUST_READ
         )
     );


     faceIOList faces
     (
         IOobject
         (
             "faces",
             "constant",
             "polyMesh",
             runTime,
             IOobject::NO_READ,
             IOobject::AUTO_WRITE
         ),
        facesCompact
     );

     faces.write();

    Info<< "end" << endl;

    return 0;
}


// ************************************************************************* //
