language: cpp
sudo: false

matrix:
  include:
    - env:
        - COMPILER=g++
      addons:
        apt:
          packages:
            - g++
      os: linux
    - env:
        - COMPILER=clang++
      os: osx

before_script:
 - echo compiler: ${COMPILER}
 - ${COMPILER} --version
 - export msRoot=${PWD}
 - mkdir src
 - mkdir thirdparty
 - mkdir -p  src/libvoxel/
 - mv *oxel*    src/libvoxel/ 
 - mv *akefile  src/libvoxel/
 - git clone https://github.com/aliraeini/zlib thirdparty/zlib
 - git clone https://github.com/aliraeini/libtiff thirdparty/libtiff
 - git clone https://github.com/aliraeini/script src/script

script: make -f src/script/Makefile.msRoot

after_script:
 - ./test.py
