name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: installPreReq
      run: sudo apt install mpi-default-dev flex libscotch-dev
    - name: make
      run: make -j
    - name: test
      run: make test
