name: make and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache lib
      uses: actions/cache@v2
      with:
        path: lib
        key: ${{ runner.os }}-lib

    - name: install prerequisites
      run: sudo apt update && sudo apt -y install mpi-default-dev flex libscotch-dev
    - name: clean
      run: make distclean, NOTE parallel make may fail due to RAM limit
    - name: make
      run: make 
    - name: test
      run: make test
